server {
    listen 80;
    server_name localhost;

    # Max size of CSV file upload
    client_max_body_size 50M;

    #Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

}
